# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 200)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-100, 120, 361, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.IMGAviso = QtWidgets.QLabel(Dialog)
        self.IMGAviso.setGeometry(QtCore.QRect(140, 10, 81, 81))
        self.IMGAviso.setText("")
        self.IMGAviso.setPixmap(QtGui.QPixmap("img/señal.ico"))
        self.IMGAviso.setScaledContents(True)
        self.IMGAviso.setObjectName("IMGAviso")
        self.TXTAviso = QtWidgets.QLabel(Dialog)
        self.TXTAviso.setGeometry(QtCore.QRect(130, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.TXTAviso.setFont(font)
        self.TXTAviso.setObjectName("TXTAviso")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Aviso"))
        self.TXTAviso.setText(_translate("Dialog", "Desea salir?"))
